language: php
php:
  - 5.6
  - 7.0
before_script:
  - curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar
  - composer require magento-ecg/coding-standard
script:
  - php phpcs.phar --standard=vendor/magento-ecg/coding-standard/EcgM2 --ignore="vendor/*" .
